exp_name: default_experiment
comment: Experiment comment goes here
data:
  images_dir: 'images'
  viewpoint_list: ['right', 'left']
  name_keys: ['name', 'viewpoint']
  n_filter_min: 2
  n_filter_max: 10
  annotation_file: test.json
  embedding_file: embeddings.pickle

lca:
  verifier_name: 'miewid'
  db_path: tmp/zebra_db

  edge_weights:
    prob_human_correct: 0.98
    augmentation_names: miewid human
    num_pos_needed: 50
    num_neg_needed: 50


  iterations:
    min_delta_converge_multiplier: 0.95
    min_delta_stability_ratio: 8
    num_per_augmentation: 2
    tries_before_edge_done: 4
    ga_iterations_before_return: 10
    ga_max_num_waiting: 50

  logging:
    log_level: INFO
    log_file: tmp/zebra.log

  drawing:
    draw_iterations: False
    drawing_prefix: drawing_lca
